version: "3.6"
services:
  postgres:
    image: postgres:latest
    container_name: "postgres"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    restart: always
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - ${DB_PORT}:${DB_PORT}
